development:
  adapter: postgresql
  encoding: unicode
  database: spree-one-page-checkout
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: spree-one-page-checkout
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: spree-one-page-checkout
  pool: 5
